. /service/common/sailor.vars

shipname=usershell
shipbins="$shipbins /bin/ksh /usr/bin/ssh /usr/bin/ssh-keygen /usr/bin/sed /usr/bin/uniq /usr/bin/xargs /usr/bin/cut /usr/bin/tr"
run_at_build="/usr/sbin/useradd -m bsd"
