. /service/common/sailor.vars

shipname=usershell
shipbins="$shipbins /usr/bin/chsh /bin/ksh /usr/bin/ssh /usr/bin/ssh-keygen /usr/bin/less /usr/bin/vi /usr/bin/ktruss /usr/bin/resize /usr/bin/reset"
