#!/bin/sh
# smolBSD quick bootstrapper
# Usage: curl -fsSL https://smolbsd.org/sh | sh

set -eu

VERS="11"
CURL="curl -fsSL"
SMOLBSD_BASE="https://smolbsd.org"
GH_BASE="https://github.com/NetBSDfr/smolBSD/releases/download/latest"
RAWGH="https://raw.githubusercontent.com/NetBSDfr/smolBSD/refs/heads/main"
START_URL="${RAWGH}/startnb.sh"
UNAME="${RAWGH}/scripts/uname.sh"
CHOUPI="${RAWGH}/service/common/choupi"

TMPDIR="$(mktemp -d -t smolbsd.XXXXXX)"
cleanup() { rm -rf "$TMPDIR"; }
trap cleanup EXIT INT TERM

cd "$TMPDIR"

mkdir -p service/common scripts
${CURL} "$CHOUPI" -o service/common/choupi
CHOUPI=y . service/common/choupi

echo "${ARROW} using temporary directory: $PWD"

OS=$(uname -s)
echo "${ARROW} checking virtualization capability"
if [ ! -e /dev/kvm ] && [ ! "$OS" = "Darwin" ] ; then
	echo "${WARN} hardware virtualization (KVM/HVF) not detected — performance may be limited." >&2
fi

ARCH="$(uname -m)"
echo "${ARROW} downloading kernel"
case "$ARCH" in
	x86_64|amd64)
		KERNEL_URL="$SMOLBSD_BASE/assets/netbsd-SMOL"
		${CURL} ${KERNEL_URL} -o kernel
		RESCUE_URL="$GH_BASE/rescue-amd64.img.xz"
		;;
	arm64|aarch64)
		KERNEL_URL="https://nycdn.netbsd.org/pub/NetBSD-daily/netbsd-${VERS}/latest/evbarm-aarch64/binary/kernel/netbsd-GENERIC64.img.gz"
		${CURL} -o- ${KERNEL_URL} | gzip -d > kernel
		RESCUE_URL="$GH_BASE/rescue-evbarm-aarch64.img.xz"
		;;
	*)
		echo "${ERROR} Unsupported architecture: $ARCH" >&2
		exit 1
		;;
esac

echo "${ARROW} downloading rescue image"
${CURL} "$RESCUE_URL" | xz -d > rescue.img
${CURL} "$START_URL" -o smol.sh
${CURL} "$UNAME" -o scripts/uname.sh
chmod +x smol.sh scripts/uname.sh

echo "${ARROW} launching smolBSD"
./smol.sh -k kernel -i rescue.img

echo
echo "${CHECK} session ended"
