. /service/common/sailor.vars

shipname=sshd
shipbins="$shipbins /bin/ksh /usr/sbin/sshd /usr/bin/ssh-keygen /usr/libexec/sshd-session /usr/libexec/sshd-auth /usr/bin/ssh"
run_at_build="mkdir -p /var/chroot/sshd"
